# Generated by Django 3.1.4 on 2020-12-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_with_skill',
            name='skill_wont_know',
        ),
        migrations.AddField(
            model_name='user_with_skill',
            name='skill_main',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_with_skill',
            name='wont_know',
            field=models.BooleanField(default=True, verbose_name='Умеешь/хочешь научиться'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name_skill',
            field=models.CharField(default='дизайн', max_length=100),
        ),
    ]
