# Generated by Django 3.1.4 on 2021-01-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_application_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='title',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
