# Generated by Django 3.1.5 on 2021-02-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210114_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender_work',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж'), ('Неважно', 'Неважно')], default='Неважно', max_length=8),
        ),
    ]
