# Generated by Django 3.1.5 on 2021-02-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210220_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender_work',
        ),
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.CharField(default='-', max_length=10000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills_know',
            field=models.CharField(default='-', max_length=20000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills_wont',
            field=models.CharField(default='-', max_length=20000),
        ),
    ]
