# Generated by Django 3.1.5 on 2021-02-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210224_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_see',
            field=models.BooleanField(default=False),
        ),
    ]
