# Generated by Django 3.1.5 on 2021-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_customuser_can_see'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='short_description',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
