# Generated by Django 3.1.5 on 2021-03-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_customuser_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='short_description',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
