# Generated by Django 3.1.5 on 2021-06-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210306_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='responding',
            field=models.IntegerField(default=0),
        ),
    ]
