# Generated by Django 3.1.5 on 2021-06-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_customuser_responding'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_ava',
            field=models.ImageField(blank=True, upload_to='static/user_pics'),
        ),
    ]
