# Generated by Django 3.1.4 on 2020-12-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201220_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Москва', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
