# Generated by Django 3.1.4 on 2021-01-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='text_zone',
            new_name='about_me',
        ),
    ]
