# Generated by Django 3.1.4 on 2021-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210104_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(default='-', max_length=1000),
            preserve_default=False,
        ),
    ]
